version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: skilltest
    container_name: skilltest
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./src/storage:/var/www/storage
    networks:
      - app-network

  db:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: skill_test
      MYSQL_USER: skill_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./src/storage/logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: